import { pageMetadata } from "@/lib/metadata";
import { LegalPage } from "@/components/privacy/LegalPage";
import styles from "@/components/privacy/LegalPage.module.css";
export const metadata = pageMetadata("Cookie Policy", "Cookie and browser storage information, optional Google Analytics and how to change your WD Marketing cookie preferences.", "/cookies");
export default function Cookies() {
  return <LegalPage title="Cookie policy" intro="You can browse the site and send an enquiry without accepting analytics. Use Cookie settings to choose whether optional measurement can run.">
    <h2>1. Cookies and similar technologies</h2><p>Cookies are small values stored by your browser. Local storage is another way a website remembers information on your device. Our controls cover optional analytics technologies as well as cookies.</p>
    <h2>2. Browser storage</h2><p>We store your cookie choice to honour it on future visits. Security services may use essential technologies to protect the site or validate a request. These functions do not require accepting optional analytics.</p>
    <div className={styles.tableWrap} role="region" aria-label="Browser storage details" tabIndex={0}><table><thead><tr><th>Item / provider</th><th>Purpose</th><th>Duration and choice</th></tr></thead><tbody>
      <tr><td><code>wd_cookie_consent</code><br/>WD Marketing local storage</td><td>Remembers your choice, consent version and date.</td><td>180 days. Essential preference storage; an expired or invalid choice is treated as no consent.</td></tr>
      <tr><td><code>_ga</code> and <code>_ga_*</code><br/>Google Analytics</td><td>Recognises a browser and maintains session information.</td><td>Only when configured and accepted. Duration is controlled by the Google tag configuration; our integration specifies 180 days without renewal on activity.</td></tr>
      <tr><td>Cloudflare security technologies</td><td>Request protection and, when enabled, Turnstile form checks. A challenge may set a clearance cookie depending on security configuration.</td><td>Conditional on the challenge and security settings. Distinct from analytics cookies.</td></tr>
    </tbody></table></div>
    <h2>3. Optional analytics</h2><p>Google Analytics 4 is delivered through Google Tag Manager only after you accept analytics and the integration is enabled. Before that, our consent integration does not load the Google Tag Manager container. Declining analytics leaves optional measurement blocked.</p><p>A saved form submission is counted separately from clicking an email, telephone or WhatsApp link. Clicking a link does not prove that a conversation or sale happened.</p>
    <h2>4. Advertising</h2><p>Advertising and remarketing tags are not enabled in the current setup. Accepting analytics does not grant advertising storage, advertising user-data or advertising personalisation consent. A future advertising integration needs updated information and an appropriate separate choice before activation.</p>
    <h2>5. Changing or withdrawing your choice</h2><p>Open <strong>Cookie settings</strong> in the footer or the navigation above. Reject optional analytics, accept it or save your choice. Closing settings without saving does not grant consent.</p><p>Withdrawal blocks new website analytics events and attempts to remove known Google Analytics cookies accessible on this domain. Browser controls can remove remaining cookies, including those this website cannot access. Withdrawal cannot remove information already sent to Google; contact us for questions about that information.</p><p>Your preference applies to this browser. Clearing website data, changing devices or reaching the 180-day expiry may cause the choice to appear again. If browser storage is unavailable, the choice applies to the current page but may not persist across visits.</p>
    <h2>6. Provider information</h2><p>Read about <a href="https://policies.google.com/technologies/cookies">Google’s cookie technologies</a> and <a href="https://developers.cloudflare.com/fundamentals/reference/policies-compliances/cloudflare-cookies/">Cloudflare cookies</a>. Our privacy policy explains enquiry data handling and your rights.</p>
  </LegalPage>;
}
