import { pageMetadata } from "@/lib/metadata";
import { LegalPage } from "@/components/privacy/LegalPage";
export const metadata = pageMetadata("Website Terms", "Terms for using the WD Marketing website, its content and project enquiry service.", "/terms");
export default function Terms() {
  return <LegalPage title="Website terms" intro="These terms explain the basis on which you may use the WD Marketing website. Paid work is governed by the separate agreement for that project.">
    <h2>1. Website use</h2><p>You may use this website for lawful purposes, including evaluating our services and sending a genuine enquiry. Do not misuse forms, interfere with the site, introduce malicious code or attempt to access information without authorisation.</p>
    <h2>2. Information and availability</h2><p>We aim to keep information accurate and useful, but it may change. General articles and examples are not advice tailored to your circumstances. We may update, suspend or withdraw parts of the site for maintenance or business reasons. Uninterrupted availability is not guaranteed.</p>
    <h2>3. Enquiries and agreements</h2><p>Sending a brief or receiving an acknowledgement does not create a paid service contract or commit you to a purchase. The applicable proposal or service agreement should define scope, fees, payments, responsibilities, deliverables and relevant cancellation arrangements before work begins.</p><p>Displayed prices or examples are subject to their stated scope and conditions. Agreed project documents determine what is included and how changes are handled. These website terms do not replace those documents or impose a separate project refund policy.</p>
    <h2>4. Marketing results</h2><p>Results depend on the market, competition, budget, offer, implementation and third-party platforms. We do not guarantee particular rankings, traffic, leads, revenue or advertising performance. Case studies describe particular work, rather than a promise of the same outcome for another business.</p>
    <h2>5. Intellectual property</h2><p>Website text, design, branding and original materials belong to their respective owners. You may view the site and keep reasonable copies for evaluating our services. Commercial reproduction, redistribution or reuse of our original materials requires permission unless the law permits it. Client names, marks and third-party materials remain the property of their owners.</p>
    <h2>6. External links</h2><p>Links to client sites, social networks and external services provide context or convenience. We do not control their content, availability or terms. A link does not transfer responsibility for those services to WD Marketing.</p>
    <h2>7. Submitted information</h2><p>Only send information you are entitled to share. Provide accurate contact details and avoid sensitive information unnecessary for an initial enquiry. Our privacy policy explains how information is handled. An enquiry is not consent to optional analytics or a marketing subscription.</p>
    <h2>8. Responsibility</h2><p>Nothing in these terms excludes or limits liability where doing so would be unlawful, including liability for fraud, fraudulent misrepresentation, or death or personal injury caused by negligence. Statutory rights that apply to you are preserved. Responsibility for paid services is addressed in the relevant service agreement.</p>
    <h2>9. Applicable law</h2><p>These website terms are governed by the law of England and Wales. Any mandatory consumer protections and rights to bring proceedings in another jurisdiction are preserved.</p>
    <h2>10. Changes and questions</h2><p>We may revise these terms as the website changes. The date above identifies the current version. Contact us using the details below with questions about these terms or permission to use website material.</p>
  </LegalPage>;
}
