import Link from "next/link";

const sections = [
  { title: "From the existing website to a focused strategy", copy: "The MB Legacy Roofing brief brought together three needs: a clearer website for London customers, a structured foundation for local SEO, and continuity when moving away from WordPress. We organised the development strategy around existing content and URLs, urgent versus planned roofing work, and the steps between discovering a service and making an enquiry. That framework shaped the implementation: preserve useful content and links, give services a clear place in the site, and make the next action easy to find." },
  { title: "Understanding roofing enquiries on mobile", copy: "A visitor dealing with a leaking roof has different priorities from a homeowner planning a tiled roof replacement. One needs a clear route to call the team; the other needs service information before requesting a quotation. We used that distinction to organise repair, replacement and emergency journeys. The responsive design brings the service message, roofing imagery and contact actions into a consistent desktop and mobile experience, with visible routes to call or request a quote." },
  { title: "A 47-route structure for services and local SEO", copy: "The resulting architecture contains 47 routes covering services, roof types and London areas. Different customer needs have defined destinations, giving the site room to explain individual services instead of relying on one homepage for every topic. Unique metadata, canonical URLs and structured data support the technical search setup. The strategy connects search-friendly organisation with useful information: service and area pages need to explain the work and its relevance to the visitor, rather than simply repeat location keywords." },
  { title: "Protecting existing links during the WordPress migration", copy: "A platform change needs a URL strategy as well as a visual redesign. The implementation includes 84 legacy redirect rules connecting old addresses to their intended destinations. Alongside canonical URLs and page-level metadata, these rules support continuity for visitors following existing links. They are migration safeguards, not proof that historic rankings or traffic have been retained. Search Console and organic landing-page performance can be used to assess that outcome after launch." },
  { title: "Connecting a fast experience with protected enquiries", copy: "The rebuild uses Next.js 16 and React 19, with Cloudflare Workers delivering the site and D1 supporting enquiries. Responsive layouts and optimised image delivery support the front-end experience. Prepared statements, rate limits, consent handling and idempotent submissions support controlled enquiry processing. These decisions connect what visitors see with what happens after they submit a request: a useful website needs both a clear contact journey and a dependable application behind it." },
  { title: "Measuring the implementation and planning the next improvements", copy: "The supplied PageSpeed Insights snapshot from 13 September 2026 records 99 desktop performance, 90 mobile performance, 97 accessibility, 96 best practices and 100 SEO. These are dated lab results; the SEO score does not measure keyword positions or organic visibility. The next measurement priorities are search impressions, relevant landing-page visits and completed enquiries. Reviewing those signals over time can guide content and conversion improvements. This case study documents the delivered platform without attributing unmeasured lead or revenue growth to the rebuild." },
];

export function RoofingApproach() {
  return <section className="section" aria-labelledby="roofing-approach-title" data-roofing-approach>
    <div className="container roofing-approach">
      <header><p className="eyebrow">Analysis · Strategy · Implementation</p><h2 id="roofing-approach-title">Roofing website design and local SEO: the thinking behind the rebuild.</h2><p>How the project requirements became a connected development strategy for MB Legacy Roofing in London.</p></header>
      <div className="roofing-approach-grid">{sections.map((section, index) => <article key={section.title}><span className="eyebrow">0{index + 1}</span><h3>{section.title}</h3><p>{section.copy}</p></article>)}</div>
      <p className="roofing-approach-links">Explore our <Link href="/services/web-conversion">website design and conversion services</Link>, <Link href="/services/seo">SEO services</Link>, or <Link href="/contact">discuss a similar project</Link>.</p>
    </div>
  </section>;
}
