const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const tools=process.env.QA_NODE_MODULES;const {chromium}=require(path.join(tools,'playwright'));const Axe=require(path.join(tools,'@axe-core/playwright')).default;
const base=process.env.QA_BASE_URL||'http://localhost:3000',out=path.resolve('qa-results');
const report={tests:[],failures:[],note:'Gallery interaction uses the production components with a mocked next/image adapter. Form provider tests use mocks, not live email delivery.'};
const check=(condition,name)=>{assert.ok(condition,name);report.tests.push(name);};
(async()=>{const browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const page=await context.newPage();page.on('pageerror',error=>report.failures.push(error.message));
 const open=async route=>{await page.goto(base+route,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.documentElement.dataset.uiReady==='true');};
 try{
  await open('/');check(await page.locator('[data-media-state="placeholder"]').count()>=3,'Homepage renders deliberate non-photographic placeholders');
  const faq=page.locator('[data-faq-section]');check(await faq.getByRole('article').count()===6,'FAQ presents all six business answers without opening an accordion');await faq.getByRole('button',{name:'Read all questions',exact:true}).click();check(await faq.getByRole('button',{name:'Read all questions',exact:true}).getAttribute('aria-pressed')==='true','FAQ readable layout is selectable');
  await open('/insights');await page.getByRole('searchbox').fill('zz-no-result');await page.getByText('No matching results.').waitFor();check(await page.locator('.resource-card').count()===0,'Insights search empty state');await page.getByRole('button',{name:'Clear filters'}).click();check(await page.locator('.resource-card').count()===3,'Clear filters restores articles');await page.getByLabel('Filter by topic').selectOption('SEO');check(await page.locator('.resource-card').count()===1,'Topic filtering');
  await open('/contact');const wizard=page.locator('[data-project-wizard]');await page.getByRole('button',{name:'Continue'}).click();check(await wizard.getByRole('alert').isVisible(),'Wizard prevents an empty first step');
  await page.getByRole('radio',{name:'SEO / Organic Growth',exact:true}).check();await page.getByRole('radio',{name:'Not sure yet',exact:true}).check();await page.getByRole('button',{name:'Continue'}).click();
  await page.getByLabel('Full name',{exact:true}).fill('Test Business');await page.getByLabel('Email',{exact:true}).fill('qa@example.com');await page.getByLabel('Company (optional)').fill('QA company');await page.getByLabel('Website (optional)').fill('https://example.com');await page.getByRole('button',{name:'Continue'}).click();await page.getByLabel('Your goal',{exact:true}).fill('Improve qualified enquiries for our service business.');
  await page.getByRole('button',{name:'Back',exact:false}).click();check(await page.getByLabel('Email',{exact:true}).inputValue()==='qa@example.com','Wizard Back preserves entered details');await page.getByRole('button',{name:'Continue'}).click();
  const responsePromise=page.waitForResponse(response=>response.url().endsWith('/api/contact')&&response.request().method()==='POST');await page.getByRole('button',{name:'Submit project brief',exact:false}).click();const response=await responsePromise;check(response.status()===503,'Unconfigured real endpoint remains closed');check(await page.getByLabel('Your goal',{exact:true}).inputValue()==='Improve qualified enquiries for our service business.','Failed delivery preserves the brief');
  check((await new Axe({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations.length===0,'Contact wizard accessibility scan');await page.screenshot({path:path.join(out,'contact-wizard.png'),fullPage:true});
  const xml=await (await context.request.get(base+'/sitemap.xml')).text();const routes=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(match=>new URL(match[1]).pathname);check(routes.length===18,'Sitemap includes 18 pages including Services overview');
  for(const route of routes){await open(route);const canonical=await page.locator('link[rel="canonical"]').getAttribute('href');check(new URL(canonical).pathname===route,`Correct canonical: ${route}`);check(await page.locator('main').count()===1,`Single main landmark: ${route}`);}
  await open('/work/stone-pro-worktops');check(await page.locator('[data-case-gallery] figure').count()===3,'All three project image slots are connected');check(await page.getByRole('button',{name:/Enlarge image/}).count()===0,'Unfinished imagery is not offered as a real project screenshot');
  await page.setViewportSize({width:390,height:844});await open('/contact');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile wizard has no page overflow');await page.screenshot({path:path.join(out,'contact-mobile.png'),fullPage:true});
  const fixture=await context.newPage();await fixture.setContent('<html><head><title>Gallery fixture</title></head><body><div id="root"></div></body></html>');
  await fixture.addStyleTag({content:':root{--line:#dce0e6;--muted:#545e6c;--surface-2:#f7f8fa}*{box-sizing:border-box}body{margin:20px;font-family:Arial}'});await fixture.addStyleTag({path:path.join(out,'gallery-fixture.css')});await fixture.addScriptTag({path:path.join(out,'gallery-fixture.js')});
  const first=fixture.getByRole('button',{name:/Enlarge image 1/});await first.click();const dialog=fixture.getByRole('dialog',{name:'Gallery test image gallery'});await dialog.waitFor();check(await dialog.isVisible(),'Image lightbox opens');await dialog.getByRole('button',{name:'Next image'}).click();check(await dialog.getByRole('status').textContent()==='2 / 2','Gallery next image');await fixture.keyboard.press('ArrowLeft');check(await dialog.getByRole('status').textContent()==='1 / 2','Gallery keyboard previous');await dialog.getByRole('button',{name:'Zoom image'}).click();check(await dialog.getByRole('button',{name:'Fit image'}).getAttribute('aria-pressed')==='true','Gallery zoom control');await fixture.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});check(!await dialog.isVisible(),'Escape closes gallery');check(await first.evaluate(el=>el===document.activeElement),'Gallery restores opener focus');check(await fixture.evaluate(()=>document.body.style.overflow!=='hidden'),'Gallery unlocks body scrolling');await fixture.locator('#broken-fixture [data-media-state="placeholder"]').waitFor();check(true,'Failed image load renders fallback');await fixture.close();
 }catch(error){report.failures.push(error.stack||error.message);}finally{await browser.close();fs.writeFileSync(path.join(out,'completion-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.failures.length)process.exitCode=1;}
})().catch(error=>{console.error(error);process.exitCode=1;});
